name: Fabric Validation Tests

on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  FabricValidation:
    runs-on: windows-latest
    outputs:
      semantic_outcome: ${{ steps.semanticmodel.outcome }}
      report_outcome: ${{ steps.report.outcome }}
      naming_outcome: ${{ steps.naming.outcome }}
      unused_outcome: ${{ steps.unused.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup folders
        run: |
          New-Item -ItemType Directory -Force -Path ./scripts/testResults
          
      - name: Run Semantic Model validation
        id: semanticmodel
        run: ./scripts/bpa-semanticmodel.ps1 -path "." -src "./src/*.SemanticModel"
        continue-on-error: true

      - name: Run Report validation
        id: report
        run: ./scripts/bpa-report.ps1 -path "." -src "./src/*.Report"
        continue-on-error: true

      - name: Check naming conventions
        id: naming
        run: ./scripts/naming_conv_test.ps1
        continue-on-error: true

      - name: Check unused fields
        id: unused
        run: ./scripts/unused-fields.ps1 -path "." -srcFolder "./src"
        continue-on-error: true
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: "**/testResults/*.xml"
          retention-days: 7

  PublishAndComment:
    runs-on: ubuntu-latest
    needs: FabricValidation
    if: always()
    permissions:
      pull-requests: write
      checks: write
      contents: read
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: downloaded-test-results

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "downloaded-test-results/**/*.xml"

      - name: Comment PR and Check Failures
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const allPassedByOutcome = 
              "${{ needs.FabricValidation.outputs.semantic_outcome }}" == "success" && 
              "${{ needs.FabricValidation.outputs.report_outcome }}" == "success" && 
              "${{ needs.FabricValidation.outputs.naming_outcome }}" == "success" && 
              "${{ needs.FabricValidation.outputs.unused_outcome }}" == "success";
              
            if (!allPassedByOutcome && "${{ github.base_ref }}" == "main") {
              core.setFailed("Al menos una validación (basada en el outcome del paso) falló. No se pueden fusionar PRs con errores a la rama.");
            }
